// Sample trip data — Family ski trip in Japan
// Each member has two flags that control their role in money flows:
//   canPay          — true means they show up in the "paid by" picker (almost always true)
//   splitsByDefault — true means they're pre-ticked in new expenses' split set
// Per-expense, any split membership can be overridden by tapping pills.
window.TRIP_DATA = {
  trip: {
    name: "Niseko Powder Week",
    location: "Niseko, Hokkaido · Japan",
    dates: "Feb 14 — Feb 21, 2026",
    baseCurrency: "JPY",
    baseCurrencySymbol: "¥",
    baseCurrencyFlag: "🇯🇵",
  },
  members: [
    // "Sponsors" — pay the card, opt out of the split by default
    { id: "P1", name: "Mum",    initials: "M", home: "AUD", homeFlag: "🇦🇺", color: "#6E2A18", canPay: true, splitsByDefault: false },
    { id: "P2", name: "Dad",    initials: "D", home: "AUD", homeFlag: "🇦🇺", color: "#2E4A3A", canPay: true, splitsByDefault: false },
    // Full participants — pay and split
    { id: "C1", name: "Alex",   initials: "A", home: "AUD", homeFlag: "🇦🇺", color: "#C9593B", canPay: true, splitsByDefault: true },
    { id: "C2", name: "Bec",    initials: "B", home: "AUD", homeFlag: "🇦🇺", color: "#5B7C6A", canPay: true, splitsByDefault: true },
    { id: "C3", name: "Chloe",  initials: "C", home: "SGD", homeFlag: "🇸🇬", color: "#8A5A8C", canPay: true, splitsByDefault: true },
    { id: "C4", name: "Ethan",  initials: "E", home: "SGD", homeFlag: "🇸🇬", color: "#3E5C78", canPay: true, splitsByDefault: true },
  ],
  marketRates: { JPY_per_AUD: 98.40, JPY_per_SGD: 114.20, AUD_per_SGD: 1.160 },
  expenses: [
    { id: "e1", date: "Feb 14", title: "Welcome dinner — Kamimura", category: "Food",
      amount: 84000, currency: "JPY", payer: "P1",
      lockedRate: { from: "AUD", rate: 97.80, note: "CBA debit card" },
      payerEquivalent: { currency: "AUD", amount: 858.90 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: true,
    },
    { id: "e2", date: "Feb 15", title: "Lift passes — 5 day", category: "Activity",
      amount: 172500, currency: "JPY", payer: "C3",
      lockedRate: { from: "SGD", rate: 113.90, note: "DBS Multiplier" },
      payerEquivalent: { currency: "SGD", amount: 1514.49 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: true,
    },
    { id: "e3", date: "Feb 15", title: "Groceries — Seicomart", category: "Food",
      amount: 12480, currency: "JPY", payer: "C2",
      lockedRate: { from: "AUD", rate: 98.10, note: "Wise card" },
      payerEquivalent: { currency: "AUD", amount: 127.22 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: false,
    },
    { id: "e4", date: "Feb 16", title: "Ski rentals (x3, Ethan has own)", category: "Activity",
      amount: 48000, currency: "JPY", payer: "C4",
      lockedRate: { from: "SGD", rate: 114.40, note: "UOB One" },
      payerEquivalent: { currency: "SGD", amount: 419.58 },
      split: { type: "equal", among: ["C1","C2","C3"] }, receipt: true,
    },
    { id: "e5", date: "Feb 17", title: "Izakaya — Bang Bang", category: "Food",
      amount: 38600, currency: "JPY", payer: "P2",
      lockedRate: { from: "AUD", rate: 98.60, note: "ING Orange" },
      payerEquivalent: { currency: "AUD", amount: 391.48 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: true,
    },
    { id: "e6", date: "Feb 18", title: "Onsen — Yukoro", category: "Activity",
      amount: 9000, currency: "JPY", payer: "P1",
      lockedRate: { from: "AUD", rate: 97.80, note: "CBA debit card" },
      payerEquivalent: { currency: "AUD", amount: 92.02 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: false,
    },
    { id: "e7", date: "Feb 18", title: "Taxi — Kutchan return", category: "Transport",
      amount: 14200, currency: "JPY", payer: "C3",
      lockedRate: { from: "SGD", rate: 113.90, note: "DBS Multiplier" },
      payerEquivalent: { currency: "SGD", amount: 124.67 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: false,
    },
    { id: "e8", date: "Feb 19", title: "Airbnb — final balance", category: "Lodging",
      amount: 420000, currency: "JPY", payer: "P2",
      lockedRate: { from: "AUD", rate: 98.10, note: "Wise card" },
      payerEquivalent: { currency: "AUD", amount: 4281.34 },
      split: { type: "equal", among: ["C1","C2","C3","C4"] }, receipt: true,
    },
  ],
};
